# Generated by Django 3.1.1 on 2024-01-31 14:27

import autoslug.fields
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('Title', models.CharField(max_length=255, verbose_name='Title of Book')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='Title', unique=True, verbose_name='Book URL Slug')),
                ('blurb', models.TextField(blank=True, verbose_name='Description')),
                ('author', models.TextField(verbose_name='Author')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
