# Generated by Django 3.1.1 on 2024-02-26 20:13

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='x', editable=False, populate_from='title', verbose_name='Book URL Slug'),
            preserve_default=False,
        ),
    ]
