# Generated by Django 3.1.1 on 2024-01-31 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Title',
            new_name='title',
        ),
    ]
