# Generated by Django 3.1.1 on 2024-02-26 20:14

from django.db import migrations

def migrate_data(apps, schema_editor):
    Author = apps.get_model('books', 'Author')
    for author in Author.objects.all():
        author.slug = f"{author.first.lower()}-{author.last.lower()}"
        author.save()

class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_author_slug'),
    ]

    operations = [
        migrations.RunPython(migrate_data, migrations.RunPython.noop),
    ]
