# Generated by Django 3.1.1 on 2024-02-26 20:16

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20240226_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True, verbose_name='Book URL Slug'),
        ),
    ]
